spring:
  application:
    name: maps-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: ${DATABASE_URL}
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
server:
  port: 8096

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URL:https://psinder-eureka.herokuapp.com}/eureka/
  instance:
    preferIpAddress: false
    nonSecurePort: 80
    hostname: ${DOMAIN_NAME:psinder-maps.herokuapp.com/}